{
 "/api/2.0/accounts/{account_id}/network-connectivity-configs/{network_connectivity_config_id}": {
  "delete": {
   "operationId": "network-connectivity-deletenetworkconnectivityconfiguration",
   "externalDocs": {
    "url": "https://docs.databricks.com/api/account/networkconnectivity/deletenetworkconnectivityconfiguration"
   },
   "x-stackQL-resource": "network_connectivity",
   "x-stackQL-method": "deletenetworkconnectivityconfiguration",
   "x-stackQL-verb": "delete",
   "x-numReqParams": 2,
   "parameters": [
    {
     "name": "account_id",
     "required": true,
     "description": "(uuid) Databricks account ID of any type. For non-E2 account types, get your account ID from the ",
     "in": "path"
    },
    {
     "name": "network_connectivity_config_id",
     "required": true,
     "description": "(uuid) Your Network Connectvity Configuration ID.",
     "in": "path"
    }
   ],
   "responses": {
    "200": {
     "description": "The network connectivity config was successfully deleted.",
     "content": {
      "application/json": {
       "schema": {
        "type": "object",
        "properties": {}
       }
      }
     }
    },
    "401": {
     "description": "The request does not have valid authentication credentials for the operation."
    },
    "404": {
     "description": "Operation was performed on a resource that does not exist."
    },
    "409": {
     "description": "Request was rejected due a conflict with an existing resource."
    },
    "500": {
     "description": "Internal error."
    }
   },
   "description": "Deletes a network connectivity configuration."
  }
 }
}