{
 "/api/2.0/accounts/{account_id}/scim/v2/ServicePrincipals": {
  "post": {
   "operationId": "service-principals-create",
   "externalDocs": {
    "url": "https://docs.databricks.com/api/account/accountserviceprincipals/create"
   },
   "x-stackQL-resource": "service_principals",
   "x-stackQL-method": "create",
   "x-stackQL-verb": "insert",
   "x-numReqParams": 1,
   "parameters": [
    {
     "name": "account_id",
     "required": true,
     "description": "uuid",
     "in": "path"
    }
   ],
   "responses": {
    "201": {
     "description": "The user creation request succeeded.",
     "content": {
      "application/json": {
       "schema": {
        "type": "object",
        "properties": {
         "id": {
          "type": "string"
         },
         "applicationId": {
          "type": "string"
         },
         "displayName": {
          "type": "string"
         },
         "roles": {
          "type": "array",
          "items": {
           "type": "object",
           "properties": {
            "$ref": {
             "type": "string"
            },
            "value": {
             "type": "string"
            },
            "display": {
             "type": "string"
            },
            "primary": {
             "type": "boolean"
            },
            "type": {
             "type": "string"
            }
           }
          }
         },
         "externalId": {
          "type": "string"
         },
         "active": {
          "type": "boolean"
         }
        }
       }
      }
     }
    },
    "400": {
     "description": "Request is invalid or malformed."
    },
    "401": {
     "description": "The request does not have valid authentication credentials for the operation."
    },
    "403": {
     "description": "Caller does not have permission to execute the specified operation."
    },
    "409": {
     "description": "Request was rejected due a conflict with an existing resource."
    },
    "500": {
     "description": "Internal error."
    }
   },
   "requestBody": {
    "required": true,
    "content": {
     "application/json": {
      "schema": {
       "type": "object",
       "properties": {
        "id": {
         "type": "integer",
         "format": "int64"
        },
        "applicationId": {
         "type": "uuid"
        },
        "displayName": {
         "type": "string"
        },
        "externalId": {
         "type": "string"
        },
        "active": {
         "type": "boolean"
        },
        "roles": {
         "type": "Array of object"
        }
       },
       "example": {
        "id": "string",
        "applicationId": "97ab27fa-30e2-43e3-92a3-160e80f4c0d5",
        "displayName": "etl-service",
        "roles": [
         {
          "$ref": "string",
          "value": "string",
          "display": "string",
          "primary": true,
          "type": "string"
         }
        ],
        "externalId": "string",
        "active": true
       }
      }
     }
    },
    "description": "Properties of the new service principal."
   },
   "description": "Creates a new service principal in the Databricks account."
  }
 }
}