{
 "/api/2.0/accounts/{account_id}/vpc-endpoints/{vpc_endpoint_id}": {
  "get": {
   "operationId": "vpc-endpoints-get",
   "externalDocs": {
    "url": "https://docs.databricks.com/api/account/vpcendpoints/get"
   },
   "x-stackQL-resource": "vpc_endpoints",
   "x-stackQL-method": "get",
   "x-stackQL-verb": "select",
   "x-numReqParams": 2,
   "parameters": [
    {
     "name": "account_id",
     "required": true,
     "description": "(uuid) Databricks account ID of any type. For non-E2 account types, get your account ID from the ",
     "in": "path"
    },
    {
     "name": "vpc_endpoint_id",
     "required": true,
     "description": "(uuid) Databricks VPC endpoint ID.",
     "in": "path"
    }
   ],
   "responses": {
    "200": {
     "description": "The VPC endpoint was successfully returned.",
     "content": {
      "application/json": {
       "schema": {
        "type": "object",
        "properties": {
         "vpc_endpoint_id": {
          "type": "string"
         },
         "vpc_endpoint_name": {
          "type": "string"
         },
         "aws_vpc_endpoint_id": {
          "type": "string"
         },
         "aws_endpoint_service_id": {
          "type": "string"
         },
         "use_case": {
          "type": "string"
         },
         "region": {
          "type": "string"
         },
         "account_id": {
          "type": "string"
         },
         "aws_account_id": {
          "type": "string"
         },
         "state": {
          "type": "string"
         }
        }
       }
      }
     }
    },
    "401": {
     "description": "The request does not have valid authentication credentials for the operation."
    },
    "404": {
     "description": "Operation was performed on a resource that does not exist."
    },
    "500": {
     "description": "Internal error."
    }
   },
   "description": "Gets a VPC endpoint configuration, which represents a"
  }
 }
}